version: "2"
services:
  example:
    build: .
    volumes:
      - ./packages/example:/working
      - /working/node_modules
    environment:
      ENV:
      DATAAPI:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_DEFAULT_REGION:
      BUCKET_NAME:
